name: Add new package(s)
description: You want to add new apps to the debloat list
title: "pkg(scope): "
labels: ["package::addition"]
body:
- type: markdown
  attributes:
    value: |
      ## Consider submitting a Pull Request

      We receive many package-related issues and it's hard to keep up. **Consider submitting a Pull Request yourself**—it helps us process changes much faster! See our [guide on how to contribute](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/wiki/How-to-contribute) for instructions.

      ---

      ## Document each package the best you can

      **List**: `Google`|`Misc`|`OEM` (manufacturer) |`AOSP`|`Pending`|`Carrier` (ISP).

      **Removal**: See the [Removal Definitions](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/wiki/Debloat-Lists#removal-definitions) on the wiki for details. **Please ensure you follow these definitions when proposing changes.**

- type: textarea
  id: package-listing
  attributes:
    label: List your packages
    description: Put the package name, list, removal and description of the package. Copy & paste the below default values when adding multiple packages.
    value: |
      - Package name: 
      - List: 
      - Removal: 
      - Description: 
  validations:
    required: true

- type: checkboxes
  id: removal-definitions
  attributes:
    label: Removal Definitions
    description: Please ensure you follow the removal definitions when proposing changes.
    options:
      - label: I've read the [Removal Definitions](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/wiki/Debloat-Lists#removal-definitions)
        required: true

- type: checkboxes
  id: acknowledgements
  attributes:
    label: Acknowledgements
    description: Your bug report will be closed if you don't follow the checklist below.
    options:
      - label: I removed all those packages on my phone. If not, why? Explain in the issue.
      - label: I'm willing to submit a Pull Request for this change.
      - label: This issue is not a duplicate of an existing one.
        required: true
      - label: I have chosen an appropriate title.
        required: true
      - label: All requested information has been provided properly.
        required: true
