name: Debloat issue report
description: Your phone has unexpected issues after debloating
title: "pkg(scope): "
labels: ["package::breakage"]
body:
- type: markdown
  attributes:
    value: |
      ## Consider submitting a Pull Request

      If you know which package caused the issue and how the documentation should be updated, **consider submitting a Pull Request yourself**—it helps us process changes much faster! See our [guide on how to contribute](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/wiki/How-to-contribute) for instructions.

- type: textarea
  id: what-happened
  attributes:
    label: Describe the problem
    description: A clear and concise description of what the problem is, including details (e.g. Android version, phone model)
  validations:
    required: true

- type: textarea
  id: suggested-solution
  attributes:
    label: You have a solution?
    description: What to do to fix the issue.

- type: textarea
  id: logfiles
  attributes:
    label: Provide logs
    description: Upload the logfile generated by UAD-ng. See https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/wiki/FAQ#where-are-the-logfiles for the location of logfiles.
  validations:
    required: true

- type: checkboxes
  id: acknowledgements
  attributes:
    label: Acknowledgements
    description: Your bug report will be closed if you don't follow the checklist below.
    options:
      - label: I'm willing to submit a Pull Request to fix the package documentation.
      - label: This issue is not a duplicate of an existing one.
        required: true
      - label: I have chosen an appropriate title.
        required: true
      - label: All requested information has been provided properly.
        required: true
